### PR TITLE
Fix process.toString() return value for debuggee process

### LINKED ISSUE #1083: Unknown named module: "../../src/methods/node.js"
## Actual Behavior
Debug does not start, instead I get this
DeepinScreenshot_select-area_20190826093343

## Expected Behavior
For debug to work

## Software versions
- React-Native VS Code extension version: 6.7.46
- VSCode version: 1.37.1
- OS platform and version: Manjaro Deepin (Arch Linux) x64
- NodeJS version: 10.16.0
- React Native version: 0.60.5
- Expo SDK version (include if relevant): Not using Expo

## Outputs (Include if relevant)
DeepinScreenshot_select-area_20190826092158

```
OS: linux x64
Adapter node: v10.11.0 x64
vscode-chrome-debug-core: 6.7.46
Starting debugger app worker.
Established a connection with the Proxy (Packager) to the React Native application
Debugger worker loaded runtime on port 13277
Unknown named module: "../../src/methods/node.js"
Module AppRegistry is not a registered callable module (calling runApplication)
```
- Output of the React-Native output channel (View -> Toggle Output -> Select React-Native in ListBox):
```
Empty
```
- Output of the Developer Tools console (Help -> Toggle Developer Tools -> Select Console tab):
```
[Extension Host] debugger listening on port 41432
workbench.main.js:sourcemap:3348 [xabikos.JavaScriptSnippets]: Unknown language in `contributes.JavaScriptSnippets.language`. Provided value: vue
_logMessageInConsole @ workbench.main.js:sourcemap:3348
workbench.main.js:sourcemap:242 [Extension Host] recovered 76 export records from cache 586c4be8e3714c3a8803e99414e5641589189960.json
workbench.main.js:sourcemap:242 [Extension Host] rejected promise not handled within 1 second: TypeError: Cannot read property 'isGitRepository' of undefined
t.log @ workbench.main.js:sourcemap:242
workbench.main.js:sourcemap:242 [Extension Host] stack trace: TypeError: Cannot read property 'isGitRepository' of undefined	at changedFiles (/home/myuser/.vscode/extensions/capaj.vscode-exports-autocomplete-0.5.4/lib/git-changed-files.js:4:14)	at require.exec.fs.readFile.then (/home/myuser/.vscode/extensions/capaj.vscode-exports-autocomplete-0.5.4/lib/exports-map.js:50:9)
t.log @ workbench.main.js:sourcemap:242
workbench.main.js:sourcemap:3414 [[object Object]]Cannot read property 'isGitRepository' of undefined
$onExtensionRuntimeError @ workbench.main.js:sourcemap:3414
workbench.main.js:sourcemap:3414 TypeError: Cannot read property 'isGitRepository' of undefined
	at changedFiles (/home/myuser/.vscode/extensions/capaj.vscode-exports-autocomplete-0.5.4/lib/git-changed-files.js:4)
	at require.exec.fs.readFile.then (/home/myuser/.vscode/extensions/capaj.vscode-exports-autocomplete-0.5.4/lib/exports-map.js:50)
$onExtensionRuntimeError @ workbench.main.js:sourcemap:3414
workbench.main.js:sourcemap:242 [Extension Host] rejected promise not handled within 1 second: Error: ENOENT: no such file or directory, open '/home/myuser/Sites/Tests/igniteAndross/node_modules/jsc-android/index.js'
t.log @ workbench.main.js:sourcemap:242
workbench.main.js:sourcemap:242 [Extension Host] stack trace: Error: ENOENT: no such file or directory, open '/home/myuser/Sites/Tests/igniteAndross/node_modules/jsc-android/index.js'
t.log @ workbench.main.js:sourcemap:242
workbench.main.js:sourcemap:1449   ERR ENOENT: no such file or directory, open '/home/myuser/Sites/Tests/igniteAndross/node_modules/jsc-android/index.js': Error: ENOENT: no such file or directory, open '/home/myuser/Sites/Tests/igniteAndross/node_modules/jsc-android/index.js'
workbench.main.js:sourcemap:242 [Extension Host] rejected promise not handled within 1 second: Error: ENOENT: no such file or directory, open '/home/myuser/Sites/Tests/igniteAndross/node_modules/react-native-linear-gradient/index'
t.log @ workbench.main.js:sourcemap:242
workbench.main.js:sourcemap:242 [Extension Host] stack trace: Error: ENOENT: no such file or directory, open '/home/myuser/Sites/Tests/igniteAndross/node_modules/react-native-linear-gradient/index'
t.log @ workbench.main.js:sourcemap:242
workbench.main.js:sourcemap:1449   ERR ENOENT: no such file or directory, open '/home/myuser/Sites/Tests/igniteAndross/node_modules/react-native-linear-gradient/index': Error: ENOENT: no such file or directory, open '/home/myuser/Sites/Tests/igniteAndross/node_modules/react-native-linear-gradient/index'
workbench.main.js:sourcemap:242 [Extension Host] rejected promise not handled within 1 second: Error: ENOENT: no such file or directory, open '/home/myuser/Sites/Tests/igniteAndross/node_modules/react-native-modal-translucent/index.js'
t.log @ workbench.main.js:sourcemap:242
workbench.main.js:sourcemap:242 [Extension Host] stack trace: Error: ENOENT: no such file or directory, open '/home/myuser/Sites/Tests/igniteAndross/node_modules/react-native-modal-translucent/index.js'
t.log @ workbench.main.js:sourcemap:242
workbench.main.js:sourcemap:1449   ERR ENOENT: no such file or directory, open '/home/myuser/Sites/Tests/igniteAndross/node_modules/react-native-modal-translucent/index.js': Error: ENOENT: no such file or directory, open '/home/myuser/Sites/Tests/igniteAndross/node_modules/react-native-modal-translucent/index.js'
workbench.main.js:sourcemap:242 [Extension Host] rejected promise not handled within 1 second: Error: ENOENT: no such file or directory, open '/home/myuser/Sites/Tests/igniteAndross/node_modules/react-native-screens/src/screens'
t.log @ workbench.main.js:sourcemap:242
workbench.main.js:sourcemap:242 [Extension Host] stack trace: Error: ENOENT: no such file or directory, open '/home/myuser/Sites/Tests/igniteAndross/node_modules/react-native-screens/src/screens'
t.log @ workbench.main.js:sourcemap:242
workbench.main.js:sourcemap:1449   ERR ENOENT: no such file or directory, open '/home/myuser/Sites/Tests/igniteAndross/node_modules/react-native-screens/src/screens': Error: ENOENT: no such file or directory, open '/home/myuser/Sites/Tests/igniteAndross/node_modules/react-native-screens/src/screens'
workbench.main.js:sourcemap:242 [Extension Host] No editors associated with document: /home/myuser/Sites/Tests/igniteAndross/jsconfig.json
t.log @ workbench.main.js:sourcemap:242
workbench.main.js:sourcemap:242 [Extension Host] No editors associated with document: /opt/visual-studio-code/resources/app/extensions/javascript/schemas/jsconfig.schema.json
t.log @ workbench.main.js:sourcemap:242
workbench.main.js:sourcemap:1449   ERR An unknown error occurred. Please consult the log for more details.
workbench.main.js:sourcemap:242 [Extension Host] (node:2642) [DEP0022] DeprecationWarning: os.tmpDir() is deprecated. Use os.tmpdir() instead.
```

I have been working on and upgrading this project since RN 0.56 or something, so the issue might be there. On a new project the debug functionality works well so I'm fairly certain there is nothing wrong with my install.
Any help or tip at this point would be most helpful, I am at my wits' end.
Thank you.

### PR DESCRIPTION
**Pull request by SounD120**
Fixes #1083 
Hiding node in debuggee process context to avoid errors in native app
Disable deprecation messages from debuggee node process with `--no-deprecation` flag
Remove hack for global variable

### CODE REVIEW

File: src/debugger/forkedAppWorker.ts [hunk 1]
```diff
@@ -80,7 +80,9 @@ export class ForkedAppWorker implements IDebuggeeWorker {
         // Note that we set --inspect-brk flag to pause the process on the first line - this is
         // required for debug adapter to set the breakpoints BEFORE the debuggee has started.
         // The adapter will continue execution once it's done with breakpoints.
-        const nodeArgs = [`--inspect-brk=${port}`, scriptToRunPath];
+        // --no-deprecation flag disables deprecation warnings that leads to errors in native app
```
Comment (ruslan-bikkinin) [inline src/debugger/forkedAppWorker.ts]:
```suggestion
        // --no-deprecation flag disables deprecation warnings like "[DEP0005] DeprecationWarning: Buffer() is deprecated..." and so on that leads to errors in native app
```
