### PR TITLE
Fix scheme parameter ambiguity

### LINKED ISSUE #989: Debugger ignoring scheme argument
## Actual Behavior
1. Debugger does not use scheme in executable path. Instead it uses the "inferred scheme", which leads to the executable not being found. 

The app builds and launches correctly.

My launch config:

```
        {
            "name": "Helper iOS - Simulator",
            "program": "${workspaceRoot}/.vscode/launchReactNative.js",
            "type": "reactnative",
            "request": "launch",
            "platform": "ios",
            "sourceMaps": true,
            "outDir": "${workspaceRoot}/.vscode/.react",
            "runArguments": [ "--scheme", "DebugHelper", "--simulator" ],
        },
```

## Expected Behavior
1. Debugger uses correct executable path

## Software versions
- React-Native VS Code extension version: 0.9.2
- VSCode version: 1.33.1
- OS platform and version: macOS 10.14.4
- NodeJS version: 11.13.0
- React Native version: 0.59.5
- Expo SDK version (include if relevant): n/a

## Outputs (Include if relevant)
- Output of the React Native tab:
```
[Info] Starting Packager

┌──────────────────────────────────────────────────────────────────────────────┐
│                                                                              │
│  Running Metro Bundler on port 8081.                                         │
│                                                                              │
│  Keep Metro running while developing on any JS projects. Feel free to        │
│  close this tab and run your own Metro instance if you prefer.               │
│                                                                              │
│  https://github.com/facebook/react-native                                    │
│                                                                              │
└──────────────────────────────────────────────────────────────────────────────┘

Looking for JS files in
   /Users/tony/Source/next/next-client 

Loading dependency graph, done.
[Info] Packager started.

[Info] Prewarming bundle cache. This may take a while ...

[Info] About to get: http://localhost:8081/index.bundle?platform=ios

 BUNDLE  [ios, dev] ./index.js ▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓ 100.0% (612/612), done.

::ffff:127.0.0.1 - - [27/Apr/2019:15:17:37 +0000] "GET /index.bundle?platform=ios HTTP/1.1" 200 4492405 "-" "-"
[Warning] The Bundle Cache was prewarmed.

[Info] Building and running application.

[Error] Error: Could not found executable in /Users/tony/Source/next/next-client/ios/build/Next/Build/Products/Debug-iphonesimulator (error code 403)
```
- Output of Debug Console:
```
OS: darwin x64
Adapter node: v10.2.0 x64
vscode-chrome-debug-core: 6.7.46
Could not debug. Could not found executable in /Users/tony/Source/next/next-client/ios/build/Next/Build/Products/Debug-iphonesimulator (error code 403)
```

- Output of the React Native - Run ios tab:
```
[Info] Starting React Native Packager.

info Found Xcode workspace Next.xcworkspace
info Building using "xcodebuild -workspace Next.xcworkspace -configuration Debug -scheme DebugHelper -destination id=33BE2562-836C-4C5E-A45C-EE21F832EFC5 -derivedDataPath build/DebugHelper"
> Running script 'Copy Firebase Config File'
> Running script 'Bundle React Native code and images'
> Running script 'Run Fabric'
> Build Succeeded
info Installing build/DebugHelper/Build/Products/Debug-iphonesimulator/NextHelper.app
info Launching com.nextforce.helper2.debug
com.nextforce.helper2.debug: 37515
```

### PR DESCRIPTION
**Pull request by ruslan-bikkinin**
This PR fixes scheme parameter ambiguity for iOS debug configuration.
Fixes #989

### CODE REVIEW

File: src/extension/generalMobilePlatform.ts [hunk 1]
```diff
@@ -81,31 +81,45 @@ export class GeneralMobilePlatform {
...
+                result = binary ? true : runArguments[optIdx + 1];
             } else {
-                for (let i = 0; i < this.runArguments.length; i++) {
-                    const arg = this.runArguments[i];
+                for (let i = 0; i < runArguments.length; i++) {
+                    const arg = runArguments[i];
                     if (arg.indexOf(optName) > -1) {
-                        result = binary ? true : arg.split("=")[1].trim();
+                        if (binary) {
+                            result = true;
```
Comment (SounD120) [inline src/extension/generalMobilePlatform.ts]: Do we need to process binary arguments like this? It is not clear why this function returns found argument or true.

Comment (ruslan-bikkinin) [reply src/extension/generalMobilePlatform.ts]: @SounD120 I've made this like that due to nature of binary parameter. Please see comment here:
https://github.com/microsoft/vscode-react-native/pull/995/files#diff-1ed5a09eac4b721889c3f7a3ae220802R109
