### PR TITLE
Fix --project-path React Native command argument handling for iOS

### LINKED ISSUE #1134: Could not find Xcode project files in
{
            "name": "Debug iOS",
            "cwd": "${workspaceFolder}",
            "type": "reactnative",
            "request": "launch",
            "platform": "ios",
            "runArguments": [
                "--project-path", "./examples/ios",
            ],
},

'iosRelativeProjectPath' option is deprecated. Please use 'runArguments' instead."
i used  runArguments, but could not _debug

`        this.iosProjectRoot = path.join(this.projectPath, this.runOptions.iosRelativeProjectPath || IOSPlatform.DEFAULT_IOS_PROJECT_RELATIVE_PATH);
` should update project-path

### PR DESCRIPTION
**Pull request by SounD120**
Fixes #1134

### CODE REVIEW

File: src/extension/ios/iOSPlatform.ts [hunk 1]
```diff
@@ -59,13 +59,10 @@ export class IOSPlatform extends GeneralMobilePlatform {
...
-        if (this.runOptions.iosRelativeProjectPath) { // Deprecated option
-            this.logger.warning(localize("iosRelativeProjectPathOptionIsDeprecatedUseRunArgumentsInstead", "'iosRelativeProjectPath' option is deprecated. Please use 'runArguments' instead."));
-        }
-
-        this.iosProjectRoot = path.join(this.projectPath, this.runOptions.iosRelativeProjectPath || IOSPlatform.DEFAULT_IOS_PROJECT_RELATIVE_PATH);
+        const iosProjectFolderPath = IOSPlatform.getOptFromRunArgs(this.runArguments, "--project-path", false);
+        this.iosProjectRoot = path.join(this.projectPath, iosProjectFolderPath || this.runOptions.iosRelativeProjectPath || IOSPlatform.DEFAULT_IOS_PROJECT_RELATIVE_PATH);
         const schemeFromArgs = IOSPlatform.getOptFromRunArgs(this.runArguments, "--scheme", false);
-        this.iosDebugModeManager  = new IOSDebugModeManager(this.iosProjectRoot, schemeFromArgs ? schemeFromArgs : this.runOptions.scheme);
+        this.iosDebugModeManager  = new IOSDebugModeManager(this.iosProjectRoot, this.projectPath, schemeFromArgs ? schemeFromArgs : this.runOptions.scheme);
```
Comment (SounD120) [inline src/extension/ios/iOSPlatform.ts]:
```suggestion
        this.iosDebugModeManager = new IOSDebugModeManager(this.iosProjectRoot, this.projectPath, schemeFromArgs ? schemeFromArgs : this.runOptions.scheme);
```
