### PR TITLE
Remove app-center-node-client from dependencies

### LINKED ISSUE #641: Debug in exponent does not run or produce any kind of error
## Actual Behavior
1. "Debug in exponent" option in vscode does not produce any result. It seems to wait for something

## Expected Behavior
1. Launch the packager and show expo QR code

## Software versions
- React-Native VS Code extension version: 0.6.1
- VSCode version: 1.20.1
- OS platform and version: OSX Sierra 10.12.6
- NodeJS version: 8.9.4
- React Native version: 0.52.0

## Outputs (Include if relevant)
- Output of the Debug Console (View -> Toggle Debug Console):
```
OS: darwin x64
Adapter node: v7.9.0 x64
vscode-chrome-debug-core: 3.23.0
```
- Output of the React-Native output channel (View -> Toggle Output -> Select React-Native in ListBox): no react-native in listbox, but some errors in extensions
```
{ Error: connect ENOENT /tmp/vscode-reactnative-b14cff98e8ffc692af84360a79508a440478f3fa67ecc65d64751eca479b886a.sock
    at Object.exports._errnoException (util.js:1050:11)
    at exports._exceptionWithHostPort (util.js:1073:20)
    at PipeConnectWrap.afterConnect [as oncomplete] (net.js:1097:14)
  code: 'ENOENT',
  errno: 'ENOENT',
  syscall: 'connect',
  address: '/tmp/vscode-reactnative-b14cff98e8ffc692af84360a79508a440478f3fa67ecc65d64751eca479b886a.sock' }
```
- Output of the Developer Tools console (Help -> Toggle Developer Tools -> Select Console tab):
```

console.ts:123 [Extension Host] Activating extension `vsmobile.vscode-react-native` failed:  Cannot find module 'app-center-node-client'
t.log @ console.ts:123
console.ts:123 [Extension Host] Here is the error stack:  Error: Cannot find module 'app-center-node-client'
	at Function.Module._resolveFilename (module.js:470:15)
	at Function.Module._load (module.js:418:25)
	at Function.o._load (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:664:413)
	at Module.require (module.js:498:17)
	at require (internal/module.js:20:19)
	at Object.<anonymous> (/Users/vmorilla/.vscode/extensions/vsmobile.vscode-react-native-0.6.1/src/extension/appcenter/api/index.js:5:34)
	at Object.<anonymous> (/Users/vmorilla/.vscode/extensions/vsmobile.vscode-react-native-0.6.1/src/extension/appcenter/api/index.js:15:3)
	at Module._compile (module.js:571:32)
	at Object.Module._extensions..js (module.js:580:10)
	at Module.load (module.js:488:32)
extensionService.ts:787 Activating extension `vsmobile.vscode-react-native` failed: Cannot find module 'app-center-node-client'.
R._logMessageInConsole @ extensionService.ts:787
```

## Additional information
This issue can be reproduced with a minimal application created with create-react-native-app

Thanks for your work!

### PR DESCRIPTION
**Pull request by ruslan-bikkinin**
This PR fixes #641.
Actually the root of the problem was that VS Code doesn't work well with "local path" dependencies like `file:` in `package.json` inside .VSIX package so we had to remove it and use relative imports in code instead.

### CODE REVIEW

**Comment by max-mironov** [comment]
Thanks for your work @ruslan-bikkinin will you take care of cordova extension then? (I believe we could have the same issue there?)

**Comment by ruslan-bikkinin** [comment]
@max-mironov yes, I will take care of it on Monday.

File: tools/gulp-extras.js [hunk 1]
```diff
@@ -79,8 +79,15 @@ var checkImports = function() {
             var workingDirectory = path.dirname(file.path);
 
             importStatements.forEach(function(importStatement) {
+
                 var modulePath = re.exec(importStatement);
                 if (modulePath && modulePath[1]) {
+
+                    // Module app-center-node-client and it's submodules are relative and doesn't use *.ts files but *.d.ts instead
+                    // so no need to check them
+                    if (modulePath[1].startsWith("../lib/app-center-node-client")) {
```
Comment (max-mironov) [inline tools/gulp-extras.js]: I'd rather not to change the logic of gulp `check-imports` function at all as there is nothing wrong with it at all.
The only thing we should do is to exclude `app-center-node-client` folder.
If we should not check imports here we should better exclude this files from `tsconfig` at all (also I believe these are js files so shouldn't be built in the end?).
