### PR TITLE
Fix fonts usage for Expo 37

### LINKED ISSUE #1252: App refuses to load with expo and @expo/vector-icons
## Actual Behavior
App refuses to load when using @expo/vector-icons (see screenshot)
 - running "expo start" gets around this and debugging works as expected
 - other issues seem to arise too from using expo eg the expo app wake lock seems to break when using debugging tools

IMG_8E954F19B919-1

## Expected Behavior
1. the app loads
2. wakelock works

## Software versions
- React-Native VS Code extension version: 0.14.2
- VSCode version: 1.44.0
- OS platform and version: MacOS 10.15.4
- NodeJS version: v13.11.0
- React Native version: [](url)
- Expo SDK version (include if relevant): 37.0.0

## Outputs (Include if relevant)
- Output of the Debug Console (View -> Toggle Debug Console):
```
console.ts:137 [Extension Host] (node:40609) [DEP0022] DeprecationWarning: os.tmpDir() is deprecated. Use os.tmpdir() instead.
t.log @ console.ts:137
log.ts:197   ERR No application in the Launch Services database matches the input criteria.: Error: No application in the Launch Services database matches the input criteria.
```
- Output of the React-Native output channel (View -> Toggle Output -> Select React-Native in ListBox):
```
[Debug] Begin to activate...

[Debug] Extension version: 0.14.2

[Debug] Projects found: 1

[Debug] Add project: /Users/nash/Projects/Expo/games_night

[Debug] React Native version: 0.61.4

[Debug] Command palette: added folder /Users/nash/Projects/Expo/games_night

[Debug] Extension messaging server started at /tmp/vscode-reactnative-2713bd8eb63549689a4e9735d187e3e0c4ad1faed6bb9e157f19512b88f9d06b.sock.

[Debug] Getting exponent dependency.

[Info] Making sure your project uses the correct dependencies for Expo. This may take a while...

Checking if this is Expo app....[Debug] 'expo' package is found in 'dependencies' section of package.json

[Debug] 'react-native' package with value 'https://github.com/expo/react-native/archive/sdk-37.0.0.tar.gz' is found in 'dependencies' section of package.json

..
[Debug] 'expo' package is found in 'dependencies' section of package.json

[Debug] 'react-native' package with value 'https://github.com/expo/react-native/archive/sdk-37.0.0.tar.gz' is found in 'dependencies' section of package.json

[Info] Starting Packager

[Debug] Executing command: /Users/nash/Projects/Expo/games_night/node_modules/.bin/react-native start --port 8081

┌──────────────────────────────────────────────────────────────────────────────┐
│                                                                              │
│  Running Metro Bundler on port 8081.                                         │
│                                                                              │
│  Keep Metro running while developing on any JS projects. Feel free to        │
│  close this tab and run your own Metro instance if you prefer.               │
│                                                                              │
│  https://github.com/facebook/react-native                                    │
│                                                                              │
└──────────────────────────────────────────────────────────────────────────────┘

Looking for JS files in
   /Users/nash/Projects/Expo/games_night 

Loading dependency graph, done.
[Info] Packager started.

[Info] Prewarming bundle cache. This may take a while ...

[Info] Building and running application.

No issue with doctor-config-json-not-readNo issue with doctor-config-json-not-readNo issue with doctor-watchman-versionNo issue with doctor-watchman-versionNo issue with doctor-problem-checking-watchman-versionNo issue with doctor-problem-checking-watchman-versionNo issue with doctor-both-app-and-exp-jsonNo issue with doctor-both-app-and-exp-jsonNo issue with doctor-unversionedNo issue with doctor-unversionedNo issue with doctor-versions-endpoint-failedNo issue with doctor-versions-endpoint-failedNo issue with doctor-invalid-sdk-versionNo issue with doctor-invalid-sdk-versionNo issue with doctor-schema-validationNo issue with doctor-schema-validationNo issue with doctor-validate-asset-fieldsNo issue with doctor-validate-asset-fieldsNo issue with doctor-schema-validation-exceptionNo issue with doctor-schema-validation-exceptionNo issue with doctor-node-modules-missingNo issue with doctor-node-modules-missingNo issue with doctor-react-native-not-installedNo issue with doctor-react-native-not-installedNo issue with doctor-config-json-not-readNo issue with doctor-config-json-not-readNo issue with doctor-watchman-versionNo issue with doctor-watchman-versionNo issue with doctor-problem-checking-watchman-versionNo issue with doctor-problem-checking-watchman-versionNo issue with doctor-both-app-and-exp-jsonNo issue with doctor-both-app-and-exp-jsonNo issue with doctor-unversionedNo issue with doctor-unversionedNo issue with doctor-versions-endpoint-failedNo issue with doctor-versions-endpoint-failedNo issue with doctor-invalid-sdk-versionNo issue with doctor-invalid-sdk-versionNo issue with doctor-schema-validationNo issue with doctor-schema-validationNo issue with doctor-validate-asset-fieldsNo issue with doctor-validate-asset-fieldsNo issue with doctor-schema-validation-exceptionNo issue with doctor-schema-validation-exceptionNo issue with doctor-node-modules-missingNo issue with doctor-node-modules-missingNo issue with doctor-react-native-not-installedNo issue with doctor-react-native-not-installedinfo Starting custom debugger by executing:, echo A debugger is not needed:  "/Users/nash/Projects/Expo/games_night"
Tunnel ready.Tunnel ready.[Info] Enable JS Debugging

 BUNDLE  [ios, dev] node_modules/expo/AppEntry.js ▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓ 100.0% (1096/1096), done.

 BUNDLE  [ios, dev] node_modules/expo/AppEntry.js ▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓ 100.0% (1/1), done.

 BUNDLE  [ios, dev] node_modules/expo/AppEntry.js ▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓ 100.0% (1/1), done.

 MAP  [ios, dev] node_modules/expo/AppEntry.js ▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓ 100.0% (1/1), done.
```
- Output of the Developer Tools console (Help -> Toggle Developer Tools -> Select Console tab):
```
console.ts:137 [Extension Host] (node:40609) [DEP0022] DeprecationWarning: os.tmpDir() is deprecated. Use os.tmpdir() instead.
t.log @ console.ts:137
log.ts:197   ERR No application in the Launch Services database matches the input criteria.: Error: No application in the Launch Services database matches the input criteria.
```

### PR DESCRIPTION
**Pull request by JiglioNero**
Fixes #1252

### CODE REVIEW

File: src/common/packager.ts [hunk 1]
```diff
@@ -393,4 +402,8 @@ export class Packager {
 
         return atomScript;
     }
+
+    private getSourceExtensions(): Array<string> {
```
Comment (SounD120) [inline src/common/packager.ts:406]: Please add a commentary with an explanation of why we need that function with a link on the original function.

File: src/common/packager.ts [hunk 2]
```diff
@@ -82,8 +82,8 @@ export class Packager {
         return this.projectPath;
     }
 
-    public getPackagerArgs(rnVersion: string, resetCache: boolean = false): Q.Promise<string[]> {
-        let args: string[] = ["--port", this.getPort().toString()];
+    public getPackagerArgs(rnVersion: string, resetCache: boolean = false): Q.Promise<any[]> {
+        let args: any[] = ["--port", this.getPort()];
```
Comment (SounD120) [inline src/common/packager.ts:86]: Why we need to change type in here?

File: src/common/packager.ts [hunk 3]
```diff
@@ -162,6 +162,15 @@ export class Packager {
 
                 let spawnOptions = { env: reactEnv };
 
+                if (this.runOptions.platform === "exponent") {
+                    let managedExtensions = this.getSourceExtensions();
```
Comment (RedMickey) [inline src/common/packager.ts:166]:
```suggestion
                    const managedExtensions = this.getSourceExtensions();
```

File: src/common/packager.ts [hunk 4]
```diff
@@ -162,12 +162,15 @@ export class Packager {
 
                 let spawnOptions = { env: reactEnv };
 
+                // Since expo@37, you must specify the sourceExts parameter for the normal loading of additional files.
```
Comment (JiglioNero) [inline src/common/packager.ts:165]:
```suggestion
                // Since expo@37, you must specify the sourceExts parameter for the normal loading of additional files:
                // (https://github.com/expo/expo-cli/blob/master/packages/xdl/src/Project.ts#L1720).
```

File: src/common/packager.ts [hunk 5]
```diff
@@ -162,6 +162,18 @@ export class Packager {
...
```
Comment (SounD120) [inline src/common/packager.ts:165]:
```suggestion
                // Since expo@37, you must specify the sourceExts parameter so that the packager can load additional files, such as custom fonts:
```

File: src/common/packager.ts [hunk 6]
```diff
@@ -393,4 +406,14 @@ export class Packager {
 
         return atomScript;
     }
+
+    // Since the array is determined either by the fact that target is bare,
+    // which is impossible in this context, or by parameters
```
Comment (SounD120) [inline src/common/packager.ts:411]: as pointed by link below

File: src/common/packager.ts [hunk 7]
```diff
@@ -411,7 +411,7 @@ export class Packager {
     // In order to solve this problem, you need to configure the packer to work with additional file extensions,
     // similar to how it was done in expo / xdl.
     private getSourceExtensions(): Array<string> {
-        // Since the array is determined by parameters
+        // Since the array is determined by parameters as pointed by link below
```
Comment (JiglioNero) [inline src/common/packager.ts:414]:
```suggestion
        // Since the array is determined by parameters (as pointed by link below)
```

File: src/common/packager.ts [hunk 8]
```diff
@@ -393,4 +406,16 @@ export class Packager {
 
         return atomScript;
     }
+
+    // Since expo 37, the packager in expo scripts has stopped correctly finding additional resources, such as custom fonts.
+    // In order to solve this problem, you need to configure the packer to work with additional file extensions,
```
Comment (SounD120) [inline src/common/packager.ts:411]:
```suggestion
    // In order to solve this problem, you need to configure the packager to work with additional file extensions,
```

File: src/common/packager.ts [hunk 9]
```diff
@@ -393,4 +406,16 @@ export class Packager {
...
+    // similar to how it was done in expo / xdl.
```
Comment (SounD120) [inline src/common/packager.ts:412]:
```suggestion
    // similar to how it was done in expo/xdl.
```

File: src/common/packager.ts [hunk 10]
```diff
@@ -393,4 +406,16 @@ export class Packager {
...
+    private getSourceExtensions(): Array<string> {
+        // Since the array is determined by parameters as pointed by link below
```
Comment (SounD120) [inline src/common/packager.ts]:
```suggestion
        // Since the array is determined by parameters (as pointed by link below)
```

File: src/common/packager.ts [hunk 11]
```diff
@@ -393,4 +406,16 @@ export class Packager {
 
         return atomScript;
     }
+
+    // Since expo 37, the packager in expo scripts has stopped correctly finding additional resources, such as custom fonts.
```
Comment (SounD120) [inline src/common/packager.ts:410]:
```suggestion
    // Since Expo 37, the packager in expo scripts has stopped correctly finding additional resources, such as custom fonts.
```

File: src/common/packager.ts [hunk 12]
```diff
@@ -162,6 +162,19 @@ export class Packager {
 
                 let spawnOptions = { env: reactEnv };
 
+                // Since expo@37, you must specify the sourceExts parameter so that the packager can load additional files, such as custom fonts:
```
Comment (SounD120) [inline src/common/packager.ts:165]:
```suggestion
                // Since Expo 37, you must specify the sourceExts parameter so that the packager can load additional files, such as custom fonts:
```

File: src/common/packager.ts [hunk 13]
```diff
@@ -393,4 +406,16 @@ export class Packager {
...
         return atomScript;
     }
+
+    // Since Expo 37, the packager in expo scripts has stopped correctly finding additional resources, such as custom fonts.
+    // In order to solve this problem, you need to configure the packager to work with additional file extensions,
+    // similar to how it was done in `expo/xdl`
+    private getSourceExtensions(): Array<string> {
+        // Since the array is determined by parameters (as pointed by link below)
+        // (https://github.com/expo/expo-cli/blob/master/packages/xdl/src/Project.ts#L1719),
+        // which are always the same, since the array that we receive in expo/xdl
```
Comment (SounD120) [inline src/common/packager.ts:416]:
```suggestion
        // which are always the same, the array that we receive in expo/xdl
```

File: test/smoke/package/config.json [hunk 14]
```diff
@@ -6,6 +6,6 @@
     "CODE_VERSION": "1.40.2",
     "EXPO_XDL_VERSION": "57.8.14",
     "RN_VERSION": "0.62.0",
-    "PURE_RN_VERSION": "0.59.8",
-    "PURE_EXPO_VERSION": "36.0.2"
+    "PURE_RN_VERSION": " 0.59.8",
```
Comment (SounD120) [inline test/smoke/package/config.json:9]:
```suggestion
    "PURE_RN_VERSION": "0.59.8",
```

File: src/common/packager.ts [hunk 15]
```diff
@@ -162,6 +162,19 @@ export class Packager {
 
                 let spawnOptions = { env: reactEnv };
 
+                // Since Expo 37, you must specify the sourceExts parameter so that the packager can load additional files, such as custom fonts:
+                // (https://github.com/expo/expo-cli/blob/master/packages/xdl/src/Project.ts#L1720).
+                // Related to https://github.com/microsoft/vscode-react-native/issues/1252
+                if (this.runOptions.platform === "exponent") {
+                    const managedExtensions = this.getSourceExtensions();
+
+                    // For normal operation, you must pass an array as an argument
```
Comment (SounD120) [inline src/common/packager.ts:171]:
```suggestion
                    // In order for the arguments to be processed normally, it is necessary to pass an array as an argument
```
