### PR TITLE
Patch for console.trace() handler to avoid throwing error on native app

### LINKED ISSUE #974: VSCode + react native tools debugging errors on console.trace()
## Actual Behavior
1. When debugging app through VSCode using React Native Tools causes the app to error when console.trace() invoked.

## Expected Behavior
1. Print out the stack trace.
2. Don't assume stack trace === error

## Software versions
- React-Native VS Code extension version: 
- VSCode version: 1.33.0
- OS platform and version: Mac OS Mojave
- NodeJS version: 11.13.0
- React Native version: 0.57.7
- Expo SDK version (include if relevant):

## Outputs (Include if relevant)
- Output of the Debug Console (View -> Toggle Debug Console):
console.trace()...
   ...trace....
Trace
    at Console.trace (internal/console/constructor.js:336:11)...
   ...trace....
```
This also makes the app screen the red error screen rendering the app unusable.

I'm trying to make better debug messaging by writing a wrapper. By putting console.log somewhere else, it loses the original context so it loses the filename and line number. I'm trying to get that back with the console.trace() but VSCode seems to assume the only reason someone would want a stack trace is because of an error.

This operates as desired if run from command line and debugging via Chrome or React Native Debugger so it is VSCode specific.

### PR DESCRIPTION
**Pull request by SounD120**
Fixes #974

### CODE REVIEW

File: src/debugger/appWorker.ts [hunk 1]
```diff
@@ -101,6 +101,27 @@ var importScripts = (function(){
     };
 })();`;
 
+    public static CONSOLE_TRACE_PATCH = `// Worker is ran as nodejs process, so console.trace() writes to stderr and it leads to error in native app
+// To avoid this console.trace() is overridden to print stacktrace via console.log()
+// Please, see Node JS implementation: https://github.com/nodejs/node/blob/master/lib/internal/console/constructor.js
+const util = require('util');
```
Comment (ruslan-bikkinin) [inline src/debugger/appWorker.ts]:
```suggestion
var formatFunc = require('util').format;
```

File: src/debugger/appWorker.ts [hunk 2]
```diff
@@ -101,6 +101,27 @@ var importScripts = (function(){
...
+console.trace = (function() {
+    return function() {
+        try {
+        var formatFunc = util.format;
```
Comment (ruslan-bikkinin) [inline src/debugger/appWorker.ts]:
```suggestion
```

File: src/debugger/appWorker.ts [hunk 3]
```diff
@@ -101,6 +101,27 @@ var importScripts = (function(){
...
 })();`;
 
+    public static CONSOLE_TRACE_PATCH = `// Worker is ran as nodejs process, so console.trace() writes to stderr and it leads to error in native app
+// To avoid this console.trace() is overridden to print stacktrace via console.log()
+// Please, see Node JS implementation: https://github.com/nodejs/node/blob/master/lib/internal/console/constructor.js
+const util = require('util');
+console.trace = (function() {
+    return function() {
+        try {
+            var formatFunc = util.format;
```
Comment (ruslan-bikkinin) [inline src/debugger/appWorker.ts]:
```suggestion
```

File: src/debugger/appWorker.ts [hunk 4]
```diff
@@ -101,6 +101,27 @@ var importScripts = (function(){
...
+            const err = {
```
Comment (ruslan-bikkinin) [inline src/debugger/appWorker.ts]:
```suggestion
            var err = {
```

File: src/debugger/appWorker.ts [hunk 5]
```diff
@@ -101,6 +101,27 @@ var importScripts = (function(){
...
+                name: 'Trace',
+                message: formatFunc.apply(null, arguments)
+                };
+            Error.stackTraceLimit = 30;
```
Comment (ruslan-bikkinin) [inline src/debugger/appWorker.ts]:
```suggestion
            // Node uses 10, but usually it's not enough for RN app trace
            Error.stackTraceLimit = 30;
```

File: test/debugger/appWorker.test.ts [hunk 6]
```diff
@@ -404,5 +404,49 @@ suite("appWorker", function () {
...
+                const script = [MultipleLifetimesAppWorker.CONSOLE_TRACE_PATCH, consoleTraceCall].join("\n");
+                const testProcess = child_process.spawn("node", ["-e", script]);
+                let procData: string = "";
+                testProcess.stdout.on("data", (data: Buffer) => {
+                    procData += data.toString();
+                });
+                testProcess.stderr.on("data", (data: Buffer) => {
+                    console.error(data.toString());
+                });
+                testProcess.on("error", (data: Buffer) => {
```
Comment (ruslan-bikkinin) [inline test/debugger/appWorker.test.ts]:
```suggestion
                testProcess.on("error", (err: Error) => {
```

File: test/debugger/appWorker.test.ts [hunk 7]
```diff
@@ -404,5 +404,49 @@ suite("appWorker", function () {
             });
         });
 
+        suite("console.trace()", function () {
+            function runScriptAndCheckOutput(expectedTraceMessage: string, consoleTraceCall: string, done: MochaDone): void {
+                const script = [MultipleLifetimesAppWorker.CONSOLE_TRACE_PATCH, consoleTraceCall].join("\n");
+                const testProcess = child_process.spawn("node", ["-e", script]);
+                let procData: string = "";
```
Comment (ruslan-bikkinin) [inline test/debugger/appWorker.test.ts]:
```suggestion
                let procData: string = "";
                let procErrData: string = "";
```

File: test/debugger/appWorker.test.ts [hunk 8]
```diff
@@ -404,5 +404,49 @@ suite("appWorker", function () {
...
+                testProcess.stdout.on("data", (data: Buffer) => {
+                    procData += data.toString();
+                });
+                testProcess.stderr.on("data", (data: Buffer) => {
+                    console.error(data.toString());
```
Comment (ruslan-bikkinin) [inline test/debugger/appWorker.test.ts]:
```suggestion
                    procErrData += data.toString();
```

File: test/debugger/appWorker.test.ts [hunk 9]
```diff
@@ -404,5 +404,49 @@ suite("appWorker", function () {
...
+                testProcess.on("error", (data: Buffer) => {
+                    console.error(data.toString());
+                });
+                testProcess.on("close", (code: number) => {
+                    assert.strictEqual(code, 0);
+                    const traceContent = procData.trim().split("\n");
+                    assert.strictEqual(traceContent[0], expectedTraceMessage);
+                    traceContent.shift();
+                    traceContent.forEach(element => {
+                        assert.strictEqual(element.trim().startsWith("at"), true, `Trace content string ${element} doesn't starts with 'at'`);
```
Comment (ruslan-bikkinin) [inline test/debugger/appWorker.test.ts]:
```suggestion
                        assert.strictEqual(element.trim().startsWith("at"), true, `Stack frame ${element} isn't started with 'at'`);
```

File: test/debugger/appWorker.test.ts [hunk 10]
```diff
@@ -404,5 +404,49 @@ suite("appWorker", function () {
...
+                    });
+                    done();
+                });
+            }
+
+            test("console.trace() patch should produce a correct output without args", (done: MochaDone) => {
```
Comment (ruslan-bikkinin) [inline test/debugger/appWorker.test.ts]:
```suggestion
            test("console.trace() patch should produce a correct output if called without args", (done: MochaDone) => {
```

File: test/debugger/appWorker.test.ts [hunk 11]
```diff
@@ -404,5 +404,49 @@ suite("appWorker", function () {
...
+                const consoleTraceCall = `console.trace();`;
+                const expectedTraceMessage = "Trace";
+                runScriptAndCheckOutput(expectedTraceMessage, consoleTraceCall, done);
+            });
+
+            test("console.trace() patch should produce a correct output with simple args", (done: MochaDone) => {
```
Comment (ruslan-bikkinin) [inline test/debugger/appWorker.test.ts]:
```suggestion
            test("console.trace() patch should produce a correct output if called with simple args", (done: MochaDone) => {
```

File: test/debugger/appWorker.test.ts [hunk 12]
```diff
@@ -404,5 +404,49 @@ suite("appWorker", function () {
...
+                const consoleTraceCall = `console.trace(\"Simple string\", 1337);`;
+                const expectedTraceMessage = "Trace: Simple string 1337";
+                runScriptAndCheckOutput(expectedTraceMessage, consoleTraceCall, done);
+            });
+
+            test("console.trace() patch should produce a correct output for a formatted string", (done: MochaDone) => {
```
Comment (ruslan-bikkinin) [inline test/debugger/appWorker.test.ts]:
```suggestion
            test("console.trace() patch should produce a correct output if called with formatted string", (done: MochaDone) => {
```

File: test/debugger/appWorker.test.ts [hunk 13]
```diff
@@ -404,5 +404,49 @@ suite("appWorker", function () {
...
+                    procData += data.toString();
+                });
+                testProcess.stderr.on("data", (data: Buffer) => {
+                    console.error(data.toString());
+                });
+                testProcess.on("error", (data: Buffer) => {
+                    console.error(data.toString());
+                });
+                testProcess.on("close", (code: number) => {
+                    assert.strictEqual(code, 0);
```
Comment (ruslan-bikkinin) [inline test/debugger/appWorker.test.ts]:
```suggestion
                    assert.strictEqual(code, 0);
                    if(procErrData !== "") {
                        assert.fail(procErrData);
                    }
```

File: test/debugger/appWorker.test.ts [hunk 14]
```diff
@@ -404,5 +404,53 @@ suite("appWorker", function () {
...
+                let procData: string = "";
+                let procErrData: string = "";
+                testProcess.stdout.on("data", (data: Buffer) => {
+                    procData += data.toString();
+                });
+                testProcess.stderr.on("data", (data: Buffer) => {
+                    procErrData += data.toString();
+                });
+                testProcess.on("error", (err: Error) => {
+                    console.error(err);
```
Comment (ruslan-bikkinin) [inline test/debugger/appWorker.test.ts]:
```suggestion
                    assert.fail(err);
```
